# Generated by Django 5.1.4 on 2025-01-13 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0044_alter_bus_bus_unit_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material_order',
            name='purchase_order',
        ),
        migrations.AddField(
            model_name='item_request',
            name='job_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.joborder'),
        ),
        migrations.AddField(
            model_name='item_request',
            name='mat_odr_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.material_order'),
        ),
        migrations.AddField(
            model_name='material_order',
            name='item_req_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.item_request'),
        ),
        migrations.AddField(
            model_name='material_order',
            name='mat_odr_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='item_request',
            name='item_req_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.employee'),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='j_o_work_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material_order',
            name='mat_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shared.material_category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material_order',
            name='mat_odr_brand',
            field=models.CharField(blank=True, default='Generic', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='material_requested',
            name='item_req_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requests', to='shared.item_request'),
        ),
    ]
