# Generated by Django 5.1.4 on 2025-01-14 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0045_remove_material_order_purchase_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_order',
            name='mat_odr_id',
        ),
        migrations.AddField(
            model_name='material_order',
            name='linked_to_po',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material_order',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_orders', to='shared.purchase_order'),
        ),
        migrations.AlterField(
            model_name='material_order',
            name='mat_odr_measurement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
