# Generated by Django 5.1.4 on 2025-01-14 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0046_remove_purchase_order_mat_odr_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material_used',
            name='mat_odr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.material_order'),
        ),
        migrations.AddField(
            model_name='material_used',
            name='mat_req_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
